image: node:latest

stages:
  - deploy

deploy_prod:
  stage: deploy
  script:
    - echo "REACT_APP_BASE_URL=https://culturenet-apis.netlify.app/.netlify/functions/api" >> ".env"
    - npm install --legacy-peer-deps
    - npm install netlify-cli -g
    - npm run build
    - netlify deploy --dir "build" --auth $AUTH_TOKEN --site $SITE_ID_PROD --prod
  only:
    - main