name: Deploy to GitHub Pages

on:
  push:
    branches:
      - stage # Runs when new changes are pushed to 'stage' branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Stage Branch
        uses: actions/checkout@v4
        with:
          ref: stage # Get the 'stage' branch

      - name: Fetch and Switch to gh-pages Branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages || git checkout -b gh-pages

      - name: Remove All Files Except CNAME
        run: |
          find . -mindepth 1 ! -name 'CNAME' -exec rm -rf {} +

      - name: Copy Files from Stage Branch’s dist/ Folder
        run: |
          git checkout stage dist\assets dist\index.html dist\favicon.ico

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Deployed from stage to gh-pages on $(date '+%Y-%m-%d %H:%M:%S IST')" || echo "No changes to commit"
          git push origin gh-pages --force
