name: Deploy to GitHub Pages

on:
  push:
    branches:
      - stage # Runs when new changes are pushed to 'stage' branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Stage Branch
        uses: actions/checkout@v4
        with:
          ref: stage # Checkout the 'stage' branch

      - name: Copy Build Files
        run: |
          # Create a temporary folder to store build files
          mkdir temp_dist
          cp -r dist/* temp_dist/

      - name: Switch to gh-pages Branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages || git checkout -b gh-pages

          # Remove all files except 'CNAME'
          find . -mindepth 1 ! -name 'CNAME' -exec rm -rf {} +

      - name: Move Copied Files to Root
        run: |
          cp -r temp_dist/* .
          rm -rf temp_dist  # Clean up temporary folder

      - name: Commit and Push Changes
        run: |
          git add --all
          git commit -m "Deployed on $(date '+%Y-%m-%d %H:%M:%S IST')" || echo "No changes to commit"
          git push origin gh-pages --force
