name: Deploy to GitHub Pages

on:
  push:
    branches:
      - stage # Runs when pushing to 'stage' branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build the Project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages || git checkout -b gh-pages

          # Remove all files EXCEPT 'CNAME'
          find . -mindepth 1 ! -name 'CNAME' -exec rm -rf {} +

          # Copy new build files from dist/ to root of gh-pages
          rsync -av dist/ . --delete

          # Stage and commit changes
          git add --all
          git commit -m "Deployed on $(date '+%Y-%m-%d %H:%M:%S IST')" || echo "No changes to commit"
          git push origin gh-pages
