name: Deploy to GitHub Pages

on:
  push:
    branches:
      - stage # Runs when you push to the 'stage' branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Stage Branch
        uses: actions/checkout@v4
        with:
          ref: stage

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Clean Install Dependencies
        run: |
          rm -rf node_modules package-lock.json  # Remove existing modules
          npm ci  # Ensure a clean install

      - name: Fix Vite Permissions
        run: chmod +x node_modules/.bin/vite # Ensure Vite can execute

      - name: Build the Project
        run: npm run build

      - name: Checkout gh-pages Branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Remove Old Files Except CNAME
        run: find . -mindepth 1 ! -name 'CNAME' -exec rm -rf {} +

      - name: Copy New Build Files from Stage Branch
        run: |
          git checkout stage -- dist
          cp -r dist/* .
          rm -rf dist  # Clean up the dist folder

      - name: Deploy to GitHub Pages
        run: |
          git add --all
          git commit -m "Deployed on $(date '+%Y-%m-%d %H:%M:%S IST')" || echo "No changes to commit"
          git push origin gh-pages --force
