name: Deploy to Production

on:
  push:
    branches:
      - stage

jobs:
  deploy_prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variable
        run: echo "REACT_APP_BASE_URL=https://culturenet-apis.netlify.app/.netlify/functions/api" >> .env

      - name: Setup Node.js
        uses: actions/setup-node@v3git
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Build the project
        run: npm run build

      - name: Deploy to Netlify Production
        run: netlify deploy --dir "dist" --auth ${{ secrets.AUTH_TOKEN }} --site ${{ secrets.SITE_ID_PROD }} --prod
